TOP = user/mpy/micropython
PY_SRC ?= $(TOP)/py
BUILD = $(TOP)/build
PY_BUILD = $(BUILD)/py

# where autogenerated header files go
HEADER_BUILD = $(BUILD)/genhdr

# file containing qstr defs for the core Python bit
PY_QSTR_DEFS = $(PY_SRC)/qstrdefs.h

$(USER): | $(HEADER_BUILD)/qstrdefs.generated.h $(HEADER_BUILD)/mpversion.h

include $(TOP)/../py.mk

# If qstr autogeneration is not disabled we specify the output header
# for all collected qstrings.
ifneq ($(QSTR_AUTOGEN_DISABLE),1)
QSTR_DEFS_COLLECTED = $(HEADER_BUILD)/qstrdefs.collected.h
endif

CP = cp
MKDIR = mkdir
SED = sed
PYTHON = python3

CFLAGS += \
	-Iuser/mpy \
	-I$(TOP) \
	-I$(BUILD) \

CSRC += \
	$(wildcard $(PY_SRC)/*.c) \
	user/mpy/mphalport.c \
	user/mpy/_frozen_mpy.c \
	$(TOP)/lib/utils/pyexec.c \
	$(TOP)/lib/mp-readline/readline.c \
	# $(TOP)/extmod/moductypes.o \
	# $(TOP)/extmod/modujson.o \
	# $(TOP)/extmod/modure.o \
	# $(TOP)/extmod/moduzlib.o \
	# $(TOP)/extmod/moduheapq.o \
	# $(TOP)/extmod/modutimeq.o \
	# $(TOP)/extmod/moduhashlib.o \
	# $(TOP)/extmod/modubinascii.o \
	# $(TOP)/extmod/virtpin.o \
	# $(TOP)/extmod/machine_mem.o \
	# $(TOP)/extmod/machine_pinbase.o \
	# $(TOP)/extmod/machine_signal.o \
	# $(TOP)/extmod/machine_pulse.o \
	# $(TOP)/extmod/machine_i2c.o \
	# $(TOP)/extmod/machine_spi.o \
	# $(TOP)/extmod/modussl_axtls.o \
	# $(TOP)/extmod/modussl_mbedtls.o \
	# $(TOP)/extmod/modurandom.o \
	# $(TOP)/extmod/moduselect.o \
	# $(TOP)/extmod/modwebsocket.o \
	# $(TOP)/extmod/modwebrepl.o \
	# $(TOP)/extmod/modframebuf.o \
	# $(TOP)/extmod/vfs.o \
	# $(TOP)/extmod/vfs_reader.o \
	# $(TOP)/extmod/vfs_fat.o \
	# $(TOP)/extmod/vfs_fat_diskio.o \
	# $(TOP)/extmod/vfs_fat_file.o \
	# $(TOP)/extmod/vfs_fat_misc.o \
	# $(TOP)/extmod/utime_mphal.o \
	# $(TOP)/extmod/uos_dupterm.o \
	# $(TOP)/lib/embed/abort_.o \

include $(TOP)/py/mkrules.mk
